# Generated by Django 5.1.1 on 2024-10-11 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_name', models.CharField(db_index=True, max_length=200)),
                ('receipe_description', models.TextField()),
                ('receipe_image', models.ImageField(upload_to='receipe/')),
                ('receipe_slug', models.SlugField(unique=True)),
                ('receipe_type', models.CharField(choices=[('veg', 'veg'), ('non-veg', 'non-veg')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrdients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=200)),
                ('reciepe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipe_ingrdients', to='home.receipe')),
            ],
        ),
    ]
